2025-03-30 16:56:20,596 - root - INFO - Running all mutations grouped by test coverage...
2025-03-30 16:56:20,596 - pypseudo.cli.main - INFO - Running all mutations for project: ../../../deepdiff
2025-03-30 16:56:20,596 - pypseudo.cli.main - INFO - Working directory: ../../../deepdiff_pypseudo_work
2025-03-30 16:56:20,596 - pypseudo.cli.main - INFO - Collecting existing mutants from instrumented code
2025-03-30 16:56:20,598 - pypseudo.cli.main - INFO - Found 261 mutants in the instrumented code
2025-03-30 16:56:20,608 - pypseudo.cli.main - INFO - Found 261 mutants in the instrumented code
2025-03-30 16:56:20,608 - pypseudo.cli.main - INFO - Running baseline tests (no mutations)
2025-03-30 16:56:20,608 - pypseudo.cli.main - INFO - Running baseline tests
2025-03-30 16:56:26,222 - pypseudo.cli.main - ERROR - Error reading JSON report: [Errno 2] No such file or directory: '../../../deepdiff_pypseudo_work/.pypseudo/pytest_report.json'
2025-03-30 16:56:26,223 - pypseudo.cli.main - ERROR - Failed to get baseline results
